const verdicts = [
    "Ja,",
    "Definitivt,",
    "Sannsynligvis,",
    "Etter all sannsynlighet,",
    "Kanskje,",
    "Muligens,",
    "Tvilsomt,",
    "Teknisk sett ikke,",
    "Kun under tvang,",
    "Kun dersom man strekker definisjonen av arbeid,",
    "Basert på tilgjengelige bevis,",
    "Ifølge våre beregninger,",
    "HR ønsker ikke å kommentere,",
    "Juridisk sett,",
    "På en god dag,",
    "I teorien,",
    "Kun på papiret,",
    "Så vidt,",
    "Motvillig,",
    "Etter sterkt press fra ledelsen,",
    "Under protest,",
    "Bare fordi noen følger med,",
    "I følge ryktene,",
    "Etter en grundig vurdering,",
    "Mest sannsynlig,",
    "Nei,",
    "Absolutt ikke,",
    "Det virker usannsynlig at",
    "Alle tegn tyder på at",
    "Det kan ikke utelukkes at"
];

const evidence = [
    "ble observert ved kaffemaskinen.",
    "har åpnet Excel.",
    "var i møte om et møte.",
    "sendte én e-post og kalte det en produktiv dag.",
    "har lest Teams-meldinger i 45 minutter.",
    "brukte hele formiddagen på å finne riktig kabel.",
    "påstår at problemet er DNS.",
    "påstår at problemet ikke er DNS.",
    "har nå konkludert med at det faktisk var DNS.",
    "ble sist sett stirrende tomt på en skjerm.",
    "har tatt dagens tredje kaffepause.",
    "har tatt dagens femte kaffepause.",
    "har opprettet en Jira-sak om problemet.",
    "har opprettet en Jira-sak om Jira-saken.",
    "jobber hjemmefra (ingen kan verifisere dette).",
    "har sagt 'jeg skal bare fikse én ting først'.",
    "har vært utilgjengelig på Teams siden kl. 09:12.",
    "har brukt 20 minutter på å velge lunsj.",
    "svarer konsekvent 'det kommer an på'.",
    "har vært på do siden forrige statusmøte.",
    "hevder å drive med strategisk tenkning.",
    "driver med viktig forskning på kaffekvalitet.",
    "ble observert på vei bort fra arbeidsoppgaver.",
    "har optimalisert noe som allerede fungerte.",
    "har brukt en time på å finne en bug som skyldtes en skrivefeil.",
    "sitter i et rom med lukkede gardiner.",
    "har åpnet terminalen for å se produktiv ut.",
    "har skrevet kode som nå må feilsøkes.",
    "har feilsøkt kode som egentlig fungerte.",
    "har foreslått å ta møtet neste uke.",
    "har foreslått å opprette en arbeidsgruppe.",
    "har foreslått å opprette en arbeidsgruppe for arbeidsgruppen.",
    "har sett på YouTube i research-øyemed.",
    "har brukt hele dagen på dokumentasjon ingen kommer til å lese.",
    "ble sist sett nær snacksautomaten.",
    "har sagt 'det fungerer på min maskin'.",
    "har rebootet problemet bort.",
    "har forsøkt å reboot'e problemet bort.",
    "har sendt en GIF i stedet for en statusoppdatering.",
    "har brukt overraskende mye tid på å velge profilbilde."
];

const confidence = [
    "Vi er sikre.",
    "Vi er ganske sikre.",
    "Vi er ikke sikre.",
    "Kilden er tvilsom.",
    "Dette er ren spekulasjon."
];
