const locations = [
    "På lokallageret",
    "På serverrommet",
    "På kjøkkenet",
    "På vei til butikken",
    "På puben",
    "På lageret",
    "På taket",
    "I møterommet",
    "I bilen",
    "På hjemmekontor",
    "På et hemmelig oppdrag",
    "I datarommet",
    "I kantina",
    "Ved kaffemaskinen",
    "På jakt etter mer pils",
    "I en Teams-samtale",
    "I en annen Teams-samtale",
    "I enda en Teams-samtale",
    "I kjelleren",
    "På vei til lunsj",
    "På vei tilbake fra lunsj",
    "På vei til en annen lunsj",
    "Hos en kunde",
    "På et ukjent sted",
    "I et annet fylke enn planlagt",
    "På observasjonspost",
    "På jakt etter riktig kabel",
    "I en teknisk diskusjon",
    "I en eksistensiell krise",
    "I nærheten av snacksautomaten",
    "På en tilfeldig parkeringsplass",
    "I en konferanse som kunne vært en e-post",
    "På vei til å fikse noe",
    "På vei tilbake etter å ha fikset noe",
    "Ved printeren",
    "I et rom ingen visste eksisterte",
    "I en Slack-tråd",
    "På internett",
    "I en annen dimensjon",
    "På ukjent lokasjon"
];

const activities = [
    "Drikker pils.",
    "Feilsøker nettverk.",
    "Ignorerer e-post.",
    "Skylder på DNS.",
    "Har åpnet Excel.",
    "Har lukket Excel.",
    "Har åpnet Excel igjen.",
    "Forsøker å huske hvorfor han gikk inn i rommet.",
    "Diskuterer kabler.",
    "Leter etter en kabel han selv la bort.",
    "Leter etter en kabel noen andre la bort.",
    "Tar en kaffepause.",
    "Tar en strategisk kaffepause.",
    "Tar en taktisk kaffepause.",
    "Skriver dokumentasjon.",
    "Ignorerer dokumentasjon.",
    "Leser loggfiler.",
    "Later som han leser loggfiler.",
    "Starter en server på nytt.",
    "Forsøker å unngå å starte en server på nytt.",
    "Forklarer hvorfor problemet ikke er hans feil.",
    "Forklarer hvorfor problemet er DNS.",
    "Forklarer hvorfor problemet ikke er DNS.",
    "Har innsett at problemet faktisk er DNS.",
    "Er i møte.",
    "Er i møte om et møte.",
    "Planlegger et møte om et møte.",
    "Har blitt distrahert av et nytt prosjekt.",
    "Har blitt distrahert av et gammelt prosjekt.",
    "Har blitt distrahert generelt.",
    "Tester noe i produksjon.",
    "Håper ingen merker at han tester i produksjon.",
    "Forsøker å finne ut hvem som gjorde endringen.",
    "Innser at det var ham selv.",
    "Ser på YouTube i research-øyemed.",
    "Har åpnet 47 nettleserfaner.",
    "Har mistet oversikten over nettleserfanene.",
    "Svarer 'det kommer an på'.",
    "Fikser ting.",
    "Skaper nye problemer."
];

const confidence = [
    "Vi er sikre.",
    "Vi er ganske sikre.",
    "Vi er ikke sikre.",
    "Kilden er tvilsom.",
    "Dette er ren spekulasjon."
];
